global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#maksim-anfilatov'
