version: '3.3'
services:

  mongo_db:
    image: mongo:${MONGO_VERSION}
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
      update_config:
        delay: 5s
        parallelism: 1
        failure_action: pause
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      front_net:

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 1s
      resources:
        limits:
          cpus: '0.30'
          memory: 300M
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    networks:
      front_net:
        aliases:
          - post
      back_net:

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 15
        delay: 1s
      resources:
        limits:
          cpus: '0.30'
          memory: 300M
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    networks:
      front_net:
        aliases:
          - comment
      back_net:


volumes:
  post_db:

networks:
  front_net:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: ${FRONT_SUBNET}
  back_net:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: ${BACK_SUBNET}
