version: '3.3'
services:

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      front_net:
      back_net:

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:

  mongodb-exporter:
    image: $USERNAME/mongodb_exporter
    networks:
      back_net:

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      back_net:

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      back_net:

  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      back_net:

volumes:
  grafana_data:
